### ISSUE TITLE
Cannot locate file on Windows

### ISSUE THREAD

**Issue by aclark02-arcus** [pharmaR/pharmapkgs#6]
Hi, I was asked to run some code on the `README`, but ran into an error at the first code chunk:

![image](https://github.com/pharmaR/pharmapkgs/assets/162465159/cd2f1402-4e4a-434f-af04-a2d4b6cb0f81)

I'm running windows, but Doug indicated that this `read.dcf()` should work regardless of OS. Thanks!

**Comment by llrs** [comment]
Hi, it would help if you provide more information.
What was your working directory at the time? What is the `traceback()` after the error? Which version of pharmapkgs did you use (main, or one of the branches)?

Note that by running that example you are trying to install from a "repository" for Ubuntu while being in a Windows, this might explain some problems but I don't think this is the root cause of this.

**Comment by aclark02-arcus** [comment]
Hi @llrs,

> What was your working directory at the time?

I cloned the repo and was in the project's root dir.

> What is the traceback() after the error? 

![image](https://github.com/pharmaR/pharmapkgs/assets/162465159/14b176a5-f21e-491b-bbf9-6c3e1d2b7e02)

>Which version of pharmapkgs did you use (main, or one of the branches)?

I attempted to execute this code on `main` and `4-risk-filter-updates`

**Comment by llrs** [comment]
Could you check that your R version is >= 4.4? It might be that you are using R < 4.4 and there isn't a "R repository" for your R version.

**Comment by aclark02-arcus** [comment]
@llrs, I'm using R `v4.3.3`!

**Comment by llrs** [comment]
I think this is the root cause: you either need to rename the folder 4.4 folder or use R >= 4.4 to use the examples.
